/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#181818",
        "surface-container-high": "#282828",
        "background": "#121212",
        "error-container": "#93000a",
        "inverse-on-surface": "#1f1f1f",
        "on-surface-variant": "#b3b3b3",
        "on-tertiary-fixed": "#002b11",
        "tertiary-fixed": "#d1fae5",
        "on-tertiary-fixed-variant": "#065f46",
        "inverse-primary": "#1db954",
        "on-secondary-fixed": "#001a42",
        "error": "#ffb4ab",
        "outline": "#3e3e3e",
        "on-primary-container": "#000000",
        "surface-container-low": "#121212",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#000000",
        "primary-fixed": "#1ed760",
        "on-error-container": "#ffdad6",
        "surface-bright": "#333333",
        "surface-tint": "#1ed760",
        "on-secondary": "#002e6a",
        "on-primary-fixed-variant": "#004d20",
        "surface-container-highest": "#333333",
        "primary": "#6366f1",
        "primary-container": "#4338ca",
        "secondary": "#a7f3d0",
        "tertiary-container": "#059669",
        "tertiary-fixed-dim": "#6ee7b7",
        "on-secondary-container": "#e6ecff",
        "on-error": "#690005",
        "outline-variant": "#282828",
        "primary-fixed-dim": "#1db954",
        "surface-variant": "#242424",
        "on-secondary-fixed-variant": "#004395",
        "secondary-container": "#047857",
        "secondary-fixed-dim": "#a7f3d0",
        "on-surface": "#ffffff",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#0a0a0a",
        "inverse-surface": "#ffffff",
        "on-tertiary-container": "#ecfdf5",
        "surface-dim": "#121212",
        "tertiary": "#10b981",
        "surface-container": "#181818",
        "on-background": "#ffffff",
        "on-tertiary": "#000000",
      },
      borderRadius: {
        none: '0',
        sm: '0.375rem',
        DEFAULT: '0.5rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.25rem",
        "gutter": "1rem",
        "margin": "1.5rem",
      },
      fontFamily: {
        sans: ["'Space Grotesk'", "'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        serif: ["'Syne'", "'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Syne'", "sans-serif"],
        "display-xl": ["'Syne'", "sans-serif"],
        "display-lg": ["'Syne'", "sans-serif"],
        "headline-lg": ["'Syne'", "sans-serif"],
        "headline-md": ["'Syne'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "title-lg": ["'Space Grotesk'", "sans-serif"],
        "title-md": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Space Grotesk'", "sans-serif"],
        "body-md": ["'Space Grotesk'", "sans-serif"],
        "body-sm": ["'Space Grotesk'", "sans-serif"],
        "label-lg": ["'JetBrains Mono'", "monospace"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "metric-mono": ["'JetBrains Mono'", "monospace"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "title-md": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "metric-mono": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "display-lg": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
      },
      boxShadow: {
        'glass-sm': '0 4px 16px 0 rgba(0, 0, 0, 0.4), inset 0 1px 1px 0 rgba(255, 255, 255, 0.12)',
        'glass-md': '0 8px 32px 0 rgba(0, 0, 0, 0.55), inset 0 1px 1px 0 rgba(255, 255, 255, 0.15)',
        'glass-lg': '0 16px 48px 0 rgba(0, 0, 0, 0.7), inset 0 1.5px 1.5px 0 rgba(255, 255, 255, 0.2)',
        'glass-glow': '0 0 40px -10px var(--primary), 0 8px 32px 0 rgba(0, 0, 0, 0.6)',
        '3d-disc': '0 25px 60px -15px rgba(0, 0, 0, 0.9), 0 0 35px -5px var(--primary)',
      },
      animation: {
        'spin-slow': 'spin 12s linear infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'mesh-float-1': 'meshFloat1 18s ease-in-out infinite',
        'mesh-float-2': 'meshFloat2 24s ease-in-out infinite',
      },
      keyframes: {
        meshFloat1: {
          '0%, 100%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%': { transform: 'translate(40px, -60px) scale(1.15)' },
        },
        meshFloat2: {
          '0%, 100%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%': { transform: 'translate(-50px, 40px) scale(1.1)' },
        },
      },
    },
  },
  plugins: [],
}
