// Design Specification Moods configuration for Timbre Studio
export const BASE_THEME = {
  bg: '#121212',
  bgPanel: '#181818',
  bgPanelHigh: '#282828',
  ink: '#ffffff',
  inkSoft: '#b3b3b3',
  rule: '#282828',
}

export const MOODS = [
  {
    id: 'chill',
    index: '03',
    tagCode: 'CHILL',
    name: 'Top Hits',
    shortName: 'Top Hits',
    badge: 'Playlist Utama',
    dspMode: 'DSP Active • Clean Hi-Fi',
    frequencyBadge: '44.1 kHz',
    flowBadge: 'Lossless Flow',
    secondaryBadge: 'Direct Stream',
    phaseSync: '100%',
    description: 'Koleksi lagu terpopuler dan terhangat dari tangga musik global dengan kualitas audio jernih.',
    accent: '#6366f1',
    accentContainer: '#4338ca',
    secondaryAccent: '#a5b4fc',
    gradient: 'from-[#1e1b4b] to-[#4338ca]',
    heroGradient: 'from-primary/10 via-surface-container-low/40 to-surface-container-lowest',
    jamendoTag: 'chillout',
    tracksCount: '0 Tracks',
    durationTotal: '0m',
    energy: 'low',
    tracks: [],
  },
  {
    id: 'energetic',
    index: '01',
    tagCode: 'VIBE',
    name: 'Midnight Groove',
    shortName: 'Midnight Groove',
    badge: 'Master Deck B',
    dspMode: 'DSP Active • Transient-Sync',
    frequencyBadge: '528 Hz',
    flowBadge: 'Pulse Dynamic',
    secondaryBadge: 'Kinetic Synth',
    phaseSync: '99.4%',
    description: 'Dynamic electronic basslines, punchy transient resonance, and driving rhythms designed for high creative inertia.',
    accent: '#B57BFF',
    accentContainer: '#8a4bf5',
    secondaryAccent: '#CABEFF',
    gradient: 'from-[#1E1035] to-[#4A154B]',
    heroGradient: 'from-[#4A154B]/20 via-surface-container-low/40 to-surface-container-lowest',
    jamendoTag: 'electronic',
    tracksCount: '0 Tracks',
    durationTotal: '0m',
    energy: 'high',
    tracks: [],
  },
  {
    id: 'warm',
    index: '02',
    tagCode: 'WARM',
    name: 'Acoustic',
    shortName: 'Acoustic',
    badge: 'Master Deck C',
    dspMode: 'DSP Active • Natural-Air',
    frequencyBadge: '440 Hz',
    flowBadge: 'Warm Harmonics',
    secondaryBadge: 'Organic Wood',
    phaseSync: '99.9%',
    description: 'Golden acoustic resonance, subtle overtone decay, and soothing organic instrumentals for grounded warmth.',
    accent: '#F59E0B',
    accentContainer: '#D97706',
    secondaryAccent: '#FDE68A',
    gradient: 'from-[#3B1D0E] to-[#D97706]',
    heroGradient: 'from-[#D97706]/15 via-surface-container-low/40 to-surface-container-lowest',
    jamendoTag: 'acoustic',
    tracksCount: '0 Tracks',
    durationTotal: '0m',
    energy: 'medium',
    tracks: [],
  },
  {
    id: 'zen',
    index: '04',
    tagCode: 'BALANCE',
    name: 'Zen Garden',
    shortName: 'Zen Garden',
    badge: 'Master Deck D',
    dspMode: 'DSP Active • Sub-Binaural',
    frequencyBadge: '396 Hz',
    flowBadge: 'Theta State',
    secondaryBadge: 'Harmonic Equilibrium',
    phaseSync: '100%',
    description: 'Meditative acoustic contours, resonant harmonic frequencies calibrated for tranquil mindfulness and restorative calm.',
    accent: '#10B981',
    accentContainer: '#059669',
    secondaryAccent: '#6EE7B7',
    gradient: 'from-[#0A2E28] to-[#10B981]',
    heroGradient: 'from-[#10B981]/15 via-surface-container-low/40 to-surface-container-lowest',
    jamendoTag: 'ambient',
    tracksCount: '0 Tracks',
    durationTotal: '0m',
    energy: 'low',
    tracks: [],
  },
]

export function getMoodById(id) {
  return MOODS.find((m) => m.id === id) || MOODS[0]
}
